service:
  port: 8080
  isGateway:
  image:
    name:
    version:
  database:
    name:
    host: postgres-service
    port: 6432
    username: rsoi
    password: rsoirsoi
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 200m
      memory: 512Mi
    
